Lambda.dfy(24,11): Error: could not prove assertion

Dafny program verifier finished with 3 verified, 1 error
