Lambda.dfy(24,11): Error: Could not prove assertion

Dafny program verifier finished with 3 verified, 1 error
